version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: QMANAGEMENTS
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: syspass
      MYSQL_DATABASE: QMANAGEMENT
      MYSQL_USER: master
      MYSQL_PASSWORD: syspass
    ports:
      - '3306:3306'
    volumes:
      - ./_data/mysql-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
  
  phpmyadmin:
    container_name: QMANAGEMENT_DEV_PHPMYADMIN
    image: phpmyadmin
    links:
      - mysql
    restart: on-failure
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306